### ISSUE TITLE
Transient failure of TestStopBufferingAndDiscard in the CI pipeline

### ISSUE THREAD

**Issue by Bartleby2718** [madelson/MedallionShell#110]
This failures very often in the CI pipeline (e.g. https://ci.appveyor.com/project/madelson/medallionshell/builds/49368379/job/5y4a5w70cght8ksd):
>  Failed TestStopBufferingAndDiscard [3 s]
  Error Message:
     can finish after read (state=0, linesWritten=144)
  Expected: True
  But was:  False
  Stack Trace:
     at Medallion.Shell.Tests.GeneralTest.TestStopBufferingAndDiscard() in C:\projects\medallionshell\MedallionShell.Tests\GeneralTest.cs:line 284
> 1)    at Medallion.Shell.Tests.GeneralTest.TestStopBufferingAndDiscard() in C:\projects\medallionshell\MedallionShell.Tests\GeneralTest.cs:line 284

FWIW, when I ran only that test alone consecutively locally, it passed 20+ times without any failures.

**Comment by Bartleby2718** [comment]
Seems like this was a known issue per https://github.com/madelson/MedallionShell/commit/aa09a7fd66cd0bb2ffa76ba911db8c632e7027ab
