### ISSUE TITLE
Cannot launch process through conhost.exe

### ISSUE THREAD

**Issue by aleksrutins** [madelson/MedallionShell#86]
I am trying to create an application that launches conhost.exe to allow the user to see the output of the processes. However, when I try to run it, I get `System.ComponentModel.Win32Exception: 'The system cannot find the file specified.'`. This is an (unsandboxed) Project Reunion/WinUI 3 application.

Here is the problem line:
```csharp
await Command.Run(@"C:\Windows\System32\conhost.exe", new string[] { ASDKLoc.Text + "\\adb.exe", "logcat" }, options => options.DisposeOnExit()).Task;
```

I am using this method because it appears that `StandardOutput.PipeToAsync()` does not trigger the `CollectionChanged` event on observable collections, which is required for binding to a XAML `ListView` data source.

This may be related to #85.

**Comment by madelson** [comment]
@aleksrutins can you post the full `Exception.ToString()` that you are seeing? Typically this exception happens when the exe can't be found, but I'd like to see the full error message to debug.

**Comment by aleksrutins** [comment]
Do you mean this?
```
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified.
  Source=System.Diagnostics.Process
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Medallion.Shell.PlatformCompatibilityHelper.SafeStart(Process process, StreamWriter& standardInput, StreamReader& standardOutput, StreamReader& standardError)
   at Medallion.Shell.ProcessCommand..ctor(ProcessStartInfo startInfo, Boolean throwOnError, Boolean disposeOnExit, TimeSpan timeout, CancellationToken cancellationToken, Encoding standardInputEncoding)
   at Medallion.Shell.Shell.Run(String executable, IEnumerable`1 arguments, Action`1 options)
   at Medallion.Shell.Command.Run(String executable, IEnumerable`1 arguments, Action`1 options)
   at FTCBuild.MainWindow.<Run_Click>d__12.MoveNext() in C:\Code\FTCBuild\FTCBuild\MainWindow.xaml.cs:line 116
```
The thing is, the command that it's trying to run is `C:\Windows\System32\conhost.exe C:\Android\platform-tools\adb.exe logcat` (I've checked), and that works when I run it in PowerShell.

**Comment by madelson** [comment]
Thanks. I wonder if it isn’t finding the file due to permissions. Does it work if you replace Command.Run with the native Process class?

**Comment by aleksrutins** [comment]
No, it doesn't.
```csharp
System.Diagnostics.Process.Start(@"C:\Windows\System32\conhost.exe", ASDKLoc.Text + @"\adb.exe logcat");
```
yields the same error. So this is probably not an issue related to this repo after all. Probably a sandboxing issue.
